entryPoints:
  http:
    address: ":80"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: phidata
    watch: true

api:
  dashboard: true
  debug: true

log:
  level: DEBUG
